name = "tapy"
main = "src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "nfc-negocio-db"
database_id = "4d264af6-3b55-4fd1-a869-d2b4dbbca455"
